[package]
name = "planetgen_engine"
version = "0.1.0"
authors = ["Matthew Nicholls <matthew.nicholls95@hotmail.co.uk>"]

[profile.release]
panic = "abort"

[dependencies]
approx = "0.1"
num = "0.1"
glium = "0.15"
cgmath = "0.11"
